# -*- coding: utf-8 -*-
"""verificar si el archivo existe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnghWpg6v14Ms0BsQ-c8Y0BwAy9caYnu
"""

#verificar si el archivo existe
from os.path import exists
ruta_completa= ("/content/mi_mapa.geojson")
exite=os.path,exists(ruta_completa)
print("existe?: ", exite)